### ISSUE TITLE
大佬好 请问权限报错是为什么?

### ISSUE THREAD

**Issue by 2563411574** [FengQuanLi/ResnetGPT#10]
C:\Users\25634\Desktop\深度学习\venv\Scripts\python.exe C:/Users/25634/Desktop/深度学习/训练数据截取_A.py
2021-01-22 17:06:03.123 | INFO     | pyminitouch.utils:is_device_connected:56 - device AQM-AL10 online
2021-01-22 17:06:03.123 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-01-22 17:06:05.137 | INFO     | pyminitouch.connection:__init__:89 - device GEY6R20327000152 bind to port 20850
2021-01-22 17:06:05.212 | INFO     | pyminitouch.connection:get_abi:35 - device GEY6R20327000152 is arm64-v8a
2021-01-22 17:06:05.285 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in GEY6R20327000152
2021-01-22 17:06:05.286 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s GEY6R20327000152 forward tcp:20850 localabstract:minitouch
2021-01-22 17:06:05.325 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20850\r\n'
2021-01-22 17:06:05.326 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s GEY6R20327000152 shell /data/local/tmp/minitouch
open: Permission denied
Unable to open device /dev/input/mice for inspectionopen: Permission denied
Unable to open device /dev/input/mouse0 for inspectionopen: Permission denied
Unable to open device /dev/input/event2 for inspectionopen: Permission denied
Unable to open device /dev/input/event3 for inspectionopen: Permission denied
Unable to open device /dev/input/event1 for inspectionopen: Permission denied
Unable to open device /dev/input/event4 for inspectionopen: Permission denied
Unable to open device /dev/input/event0 for inspectionUnable to find a suitable touch device
Traceback (most recent call last):
  File "C:/Users/25634/Desktop/深度学习/训练数据截取_A.py", line 186, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "C:\Users\25634\Desktop\深度学习\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\pyminitouch\connection.py", line 103, in __init__
    ), "minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11"
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11

**Comment by FengQuanLi** [comment]
估计还是minitouch没有安装好

**Comment by GuoyaoShen** [comment]
the "permission denied" error might because "minitouch can't handle Android 10 by default" as already stated in the [minitouch repo](https://github.com/openstf/minitouch), try to use another phone with android 9 or lower version.

**Comment by 2563411574** [comment]
1
