### ISSUE TITLE
出现RuntimeError: Invalid device, must be cuda device 报错

### ISSUE THREAD

**Issue by 2563411574** [FengQuanLi/ResnetGPT#12]
具体报错如下
这是第一个错误
Type A touch device huawei,ts_kit (720x1560 with 11 contacts) detected on /dev/input/event2 (score 21059)
Note: hard-limiting maximum number of contacts to 10
这是第二个错误
Connection established
Traceback (most recent call last):
  File "C:/Users/25634/Desktop/深度学习/训练数据截取_A.py", line 188, in <module>
    mod = torchvision.models.resnet101(pretrained=True).eval().cuda(device).requires_grad_(False)
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\torch\nn\modules\module.py", line 463, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\torch\nn\modules\module.py", line 359, in _apply
    module._apply(fn)
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\torch\nn\modules\module.py", line 381, in _apply
    param_applied = fn(param)
  File "C:\Users\25634\Desktop\深度学习\venv\lib\site-packages\torch\nn\modules\module.py", line 463, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: Invalid device, must be cuda device

[http://xiazai.cnsafet.cn/1.png](url)

**Comment by 2563411574** [comment]
http://xiazai.cnsafet.cn/1.png 这是报错截图

**Comment by FengQuanLi** [comment]
第一个错误更像是一个警告，因为程序在往下执行
第二个错误可能是因为
1、不是英伟达显卡
2、没有装好cuda
3、pytorch和cuda版本不对应

**Comment by 2563411574** [comment]
应该是1.不是英伟达显卡导致的
那么有什么办法可以解决吗？
比如用CPU计算？
要如何处理呢？

**Comment by xijinmu** [comment]
> 应该是1.不是英伟达显卡导致的
> 那么有什么办法可以解决吗？
> 比如用CPU计算？
> 要如何处理呢？

GPU运行都费劲，别说CPU了。。。

**Comment by 2563411574** [comment]
> > 应该是1.不是英伟达显卡导致的
> > 那么有什么办法可以解决吗？
> > 比如用CPU计算？
> > 要如何处理呢？
> 
> GPU运行都费劲，别说CPU了。。。

额 我已经运行成功了 用CPU…
只需要把cuda禁用就行了 CPU占用差不多50% 也没有想象的那么高 还是非常流畅的
