### ISSUE TITLE
执行“训练数据截取_A”后报错，没看到界面，也不知道配置对不对

### ISSUE THREAD

**Issue by ghost** [FengQuanLi/ResnetGPT#17]
执行“训练数据截取_A”后报错:
Traceback (most recent call last):
  File "E:\AI王者荣耀\ResnetGPT-master\训练数据截取_A.py", line 3, in <module>
    import torchvision
  File "E:\AI王者荣耀\ResnetGPT-master\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "E:\AI王者荣耀\ResnetGPT-master\torchvision\models\__init__.py", line 1, in <module>
    from .alexnet import *
  File "E:\AI王者荣耀\ResnetGPT-master\torchvision\models\alexnet.py", line 1, in <module>
    import torch.nn as nn
  File "E:\AI王者荣耀\ResnetGPT-master\torch\__init__.py", line 218, in <module>
    ''').strip()) from None
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

我把下的第三方库文件夹也放在项目根目录里，scrcpy环境变量也配置好了但是也报错：
------------------------------------------
错误: 没有找到进程 "scrcpy.exe"。
错误: 无法终止进程 "adb.exe"，其 PID 为 15344。
原因: 拒绝访问。
'scrcpy' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
-------------------------------------------
或者这样：
INFO: scrcpy 1.17 <https://github.com/Genymobile/scrcpy>
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
----------------------------------------------
另外那个_DEVICE_ID是怎么找的，因为没一个程序运行起来，界面也看不到。

**Comment by ghost** [comment]
2462639573这是我QQ，能运行的小伙伴加一下我，帮我解决一下，谢谢！

**Comment by XXGUI** [comment]
> 执行“训练数据截取_A”后报错:
> Traceback (most recent call last):
> File "E:\AI王者荣耀\ResnetGPT-master\训练数据截取_A.py", line 3, in
> import torchvision
> File "E:\AI王者荣耀\ResnetGPT-master\torchvision__init__.py", line 1, in
> from torchvision import models
> File "E:\AI王者荣耀\ResnetGPT-master\torchvision\models__init__.py", line 1, in
> from .alexnet import *
> File "E:\AI王者荣耀\ResnetGPT-master\torchvision\models\alexnet.py", line 1, in
> import torch.nn as nn
> File "E:\AI王者荣耀\ResnetGPT-master\torch__init__.py", line 218, in
> ''').strip()) from None
> ImportError: Failed to load PyTorch C extensions:
> It appears that PyTorch has loaded the `torch/_C` folder
> of the PyTorch repository rather than the C extensions which
> are expected in the `torch._C` namespace. This can occur when
> using the `install` workflow. e.g.
> $ python setup.py install && python -c "import torch"
> 
> ```
> This error can generally be solved using the `develop` workflow
>     $ python setup.py develop && python -c "import torch"  # This should succeed
> or by running Python from a different directory.
> ```
> 
> ## 我把下的第三方库文件夹也放在项目根目录里，scrcpy环境变量也配置好了但是也报错：
> ## 错误: 没有找到进程 "scrcpy.exe"。
> 错误: 无法终止进程 "adb.exe"，其 PID 为 15344。
> 原因: 拒绝访问。
> 'scrcpy' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> ## 或者这样：
> INFO: scrcpy 1.17 https://github.com/Genymobile/scrcpy
> adb: error: failed to get feature set: no devices/emulators found
> ERROR: "adb push" returned with value 1
> 另外那个_DEVICE_ID是怎么找的，因为没一个程序运行起来，界面也看不到。

这个问题大概率是环境不对造成的错误您可能需要重新装一下torch库了
