### ISSUE TITLE
AIDA64里面的安卓ID不是那个device_id?

### ISSUE THREAD

**Issue by Natsuki-Hui** [FengQuanLi/ResnetGPT#27]
adb.exe: device 'e6bf1f555f54eb85' not found
Traceback (most recent call last):
  File "D:\ResnetGPT-master\训练数据截取_A.py", line 186, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "D:\ResnetGPT-master\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\pyminitouch\connection.py", line 84, in __init__
    assert is_device_connected(device_id)

**Comment by FengQuanLi** [comment]
device_id通过 adb devices 命令获取
