### ISSUE TITLE
训练数据截取A时报错

### ISSUE THREAD

**Issue by CSong98** [FengQuanLi/ResnetGPT#35]
Traceback (most recent call last):
  File "D:\代码\ResnetGPT-master\训练数据截取_A.py", line 5, in <module>
    from Batch import create_masks
  File "D:\代码\ResnetGPT-master\Batch.py", line 32, in <module>
    class MyIterator(data.Iterator):
AttributeError: module 'torchtext.data' has no attribute 'Iterator'

显示在class MyIterator(data.Iterator):这个类里面没有iterator属性，求解

**Comment by CSong98** [comment]
你好我刚刚解决了这个问题，通过群里的doc，但是我现在出现了新问题
Connection established
Traceback (most recent call last):
  File "D:\代码\ResnetGPT-master\训练数据截取_A.py", line 188, in <module>
    mod = torchvision.models.resnet101(pretrained=True).eval().cuda(device).requires_grad_(False)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 387, in _apply
    module._apply(fn)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 409, in _apply
    param_applied = fn(param)
  File "C:\Python39\lib\site-packages\torch\nn\modules\module.py", line 491, in <lambda>
    return self._apply(lambda t: t.cuda(device))
**RuntimeError: Invalid device, must be cuda device**
我通过英伟达官网安装了驱动，但是仍然无法解决

**Comment by CSong98** [comment]
已解决，pytorch 版本和cuda版本不匹配，去pytorch官网选择版本下载一下重新安装就可以了，装好了测试一下
import torch

print(torch.cuda.is_available())
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))


这几行代码能跑，cuda的问题就解决了
