### ISSUE TITLE
运行后找不到设备：error: device '***********' not found

### ISSUE THREAD

**Issue by XXGUI** [FengQuanLi/ResnetGPT#36]
两个种方式均为找不到设备，有没有人遇到过这样的问题。又是怎么解决的呢

手动填写设备ID的错误内容：
D:\Python\Python37\python.exe D:/Python/AI王者荣耀-m/ResnetGPT/训练数据截取_A.py
设备ID= ***********
error: device '**********' not found
Traceback (most recent call last):
  File "D:/Python/AI王者荣耀-m/ResnetGPT/训练数据截取_A.py", line 194, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "D:\Python\AI王者荣耀-m\ResnetGPT\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\connection.py", line 84, in __init__
    assert is_device_connected(device_id)
AssertionError

自动获取设备ID出现错误：
2021-06-03 10:01:19.255 | INFO     | pyminitouch.utils:is_device_connected:56 - device 手机型号 online
2021-06-03 10:01:19.255 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-06-03 10:01:21.256 | INFO     | pyminitouch.connection:__init__:89 - device ['4c9f728c'] bind to port 20872
2021-06-03 10:01:21.294 | INFO     | pyminitouch.connection:get_abi:35 - device ['4c9f728c'] is error: device '['********']' not found
2021-06-03 10:01:21.382 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in ['********']
Traceback (most recent call last):
  File "D:/Python/AI王者荣耀-m/ResnetGPT/训练数据截取_A.py", line 194, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "D:\Python\AI王者荣耀-m\ResnetGPT\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\connection.py", line 95, in __init__
    self._forward_port()
  File "D:\Python\Python37\lib\site-packages\pyminitouch\connection.py", line 128, in _forward_port
    logger.debug("forward command: {}".format(" ".join(command_list)))
TypeError: sequence item 2: expected str instance, list found

**Comment by FengQuanLi** [comment]
⦁	_DEVICE_ID获取方式。
adb devices

**Comment by XXGUI** [comment]
> ⦁ _DEVICE_ID获取方式。
> adb devices

试过这个方式的ID了的，也是找不到设备

**Comment by XXGUI** [comment]
> ⦁ _DEVICE_ID获取方式。
> adb devices

我又行了，这ID还不能改大小写。。。。我这改了就读不到了
