### ISSUE TITLE
启动后出现错误： "minitouch did not work.see ************

### ISSUE THREAD

**Issue by XXGUI** [FengQuanLi/ResnetGPT#37]
提示minitouch没在工作，进了提示的'https://github.com/williamfzc/pyminitouch/issues/11'网址也没找到有效的解决方案

2021-06-04 09:06:47.653 | INFO     | pyminitouch.utils:is_device_connected:56 - device SKR-A0 online
2021-06-04 09:06:47.653 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-06-04 09:06:49.661 | INFO     | pyminitouch.connection:__init__:89 - device ***** bind to port 20487
2021-06-04 09:06:49.759 | INFO     | pyminitouch.connection:get_abi:35 - device ***** is arm64-v8a
2021-06-04 09:06:49.838 | INFO     | pyminitouch.connection:__init__:27 - minitouch already existed in *****
2021-06-04 09:06:49.838 | DEBUG    | pyminitouch.connection:_forward_port:128 - forward command: adb -s ***** forward tcp:20487 localabstract:minitouch
2021-06-04 09:06:49.864 | DEBUG    | pyminitouch.connection:_forward_port:130 - output: b'20487\r\n'
2021-06-04 09:06:49.864 | INFO     | pyminitouch.connection:_start_mnt:141 - start minitouch: adb -s ***** shell /data/local/tmp/minitouch
/data/local/tmp/minitouch[5]: syntax error: unexpected 'newline'
Traceback (most recent call last):
  File "D:/PythonWork/AI王者荣耀/ResnetGPT/训练数据截取_A.py", line 195, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "D:\PythonWork\AI王者荣耀\ResnetGPT\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "D:\Python\Python37\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "D:\Python\Python37\lib\site-packages\pyminitouch\connection.py", line 103, in __init__
    ), "minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11"
AssertionError: minitouch did not work. see https://github.com/williamfzc/pyminitouch/issues/11

**Comment by CSong98** [comment]
应该是需要手动给手机或者模拟器安装一下minitouch

**Comment by XXGUI** [comment]
> 应该是需要手动给手机或者模拟器安装一下minitouch

对的，这个要挂梯子才能自动安装好，要不然只能自己在手机上装好
