### ISSUE TITLE
pywin32：pip和conda的冲突

### ISSUE THREAD

**Issue by greenhandzdl** [FengQuanLi/ResnetGPT#40]
`
Traceback (most recent call last):
  File "/home/greenhandzdl/Desktop/ResnetGPT/训练数据截取_A.py", line 12, in <module>
    from 运行辅助 import *
  File "/home/greenhandzdl/Desktop/ResnetGPT/运行辅助.py", line 1, in <module>
    import win32gui, win32ui, win32con
ModuleNotFoundError: No module named 'win32gui'
`
然后我
`
┌─[root@GreenhandzdlsWindow]─[/home/greenhandzdl/Desktop/ResnetGPT]
└──╼ #pip install win32gui win32ui   win32con
ERROR: Introspect error on :1.1:/modules/kwalletd5: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
WARNING: Keyring is skipped due to an exception: Failed to open keyring: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.1 was not provided by any .service files.
Collecting win32gui
  Using cached win32gui-221.5.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpl4bralee_in_process.py get_requires_for_build_wheel /tmp/tmp6ks_qi5p
       cwd: /tmp/pip-install-oev5_sxb/win32gui_5a95d9aa821a43098bbd50354ab86e00
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/tmp/tmpl4bralee_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpl4bralee_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpl4bralee_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-1x59y7q1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-1x59y7q1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-1x59y7q1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-1x59y7q1/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 27, in <module>
      from win32.distutils.gui import win32gui_build_ext
    File "/tmp/pip-install-oev5_sxb/win32gui_5a95d9aa821a43098bbd50354ab86e00/win32/distutils/gui.py", line 4, in <module>
      import winreg
  ModuleNotFoundError: No module named 'winreg'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b8/75/7bed82934e51903f9d48b26b3996161bb2dce1731607b4bb7fd26003ed3e/win32gui-221.5.tar.gz#sha256=b2be0885d526d70b3f9a62f4005e9452cdb4bce67e117f4c14e7aa684bc5b2a5 (from https://pypi.org/simple/win32gui/). Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpl4bralee_in_process.py get_requires_for_build_wheel /tmp/tmp6ks_qi5p Check the logs for full command output.
  Using cached win32gui-221.4.tar.gz (605 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpotx8n9vp_in_process.py get_requires_for_build_wheel /tmp/tmp7riwy8s4
       cwd: /tmp/pip-install-oev5_sxb/win32gui_735679b337704fcd8b411d70877080db
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/tmp/tmpotx8n9vp_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpotx8n9vp_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpotx8n9vp_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-tjjj0a_u/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-tjjj0a_u/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-tjjj0a_u/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-tjjj0a_u/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 26, in <module>
      from win32.distutils.gui import win32gui_build_ext
    File "/tmp/pip-install-oev5_sxb/win32gui_735679b337704fcd8b411d70877080db/win32/distutils/gui.py", line 4, in <module>
      import winreg
  ModuleNotFoundError: No module named 'winreg'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/82/93/e3908020a82c2a628ecc05faad79aa947f22eee672f272622ca7ad4d7bf3/win32gui-221.4.tar.gz#sha256=91d1df0a00c8dbbc82bfd8a04039bd26a96d2119307ceb695d1b356f478cecee (from https://pypi.org/simple/win32gui/). Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpotx8n9vp_in_process.py get_requires_for_build_wheel /tmp/tmp7riwy8s4 Ch``eck the logs for full command output.
  Using cached win32gui-221.3.tar.gz (614 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpqycdzqy1_in_process.py get_requires_for_build_wheel /tmp/tmp0kin20os
       cwd: /tmp/pip-install-oev5_sxb/win32gui_4a6253462a3f46d285dee8031f929b6d
  Complete output (20 lines):
  Traceback (most recent call last):
    File "/tmp/tmpqycdzqy1_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpqycdzqy1_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpqycdzqy1_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-xi5r_enz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-xi5r_enz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-xi5r_enz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-xi5r_enz/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 26, in <module>
      from win32.distutils.gui import win32gui_build_ext
    File "/tmp/pip-install-oev5_sxb/win32gui_4a6253462a3f46d285dee8031f929b6d/win32/distutils/gui.py", line 4, in <module>
      import winreg
  ModuleNotFoundError: No module named 'winreg'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/58/d8/727d452ea900aa4be08b0e264e4a12d1f04e51b60f46ce01e0996f071f85/win32gui-221.3.tar.gz#sha256=d6ebe58330480bde71ad93c0e67b31b58ec6091e281d944f1cb529f4e9611c00 (from https://pypi.org/simple/win32gui/). Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpqycdzqy1_in_process.py get_requires_for_build_wheel /tmp/tmp0kin20os Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement win32gui
ERROR: No matching distribution found for win32gui
`

**Comment by FengQuanLi** [comment]
可能是缺少模块
pip install pywin32
试试

**Comment by greenhandzdl** [comment]
> 可能是缺少模块
> pip install pywin32
> 试试
`
PS C:\Windows\system32> conda install pywin32
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

PS C:\Windows\system32> pip3 install pywin32
Collecting pywin32
  Downloading pywin32-301-cp39-cp39-win_amd64.whl (9.3 MB)
     |████████████████████████████████| 9.3 MB 1.5 MB/s
Installing collected packages: pywin32
Successfully installed pywin32-301
PS C:\Windows\system32> python
Python 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> import win32gui
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing win32gui: 找不到指定的程序。
`

**Comment by greenhandzdl** [comment]
我觉得比较疑惑的是，我安装了pywin32结果识别不出来，我想整下conda，结果提醒我有这玩意。
我感觉很困惑，我也是跟着视频开始整的。
