### ISSUE TITLE
奇怪的报错，是否因为pytorch1.9版本太高了？

### ISSUE THREAD

**Issue by gavin231mao** [FengQuanLi/ResnetGPT#41]
`> C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\python.exe "D:/@3 深度学习/案例/@6 WZCQ-main 用强化学习训练AI玩王者荣耀/WZCQ-main/训练数据截取_A.py"
loading pretrained weights...
Traceback (most recent call last):
  File "D:/@3 深度学习/案例/@6 WZCQ-main 用强化学习训练AI玩王者荣耀/WZCQ-main/训练数据截取_A.py", line 50, in <module>
    智能体 = 智能体(动作数=7, 并行条目数=条数,
  File "D:\@3 深度学习\案例\@6 WZCQ-main 用强化学习训练AI玩王者荣耀\WZCQ-main\模型_策略梯度.py", line 268, in __init__
    model = get_model(config, 130, 模型名称)
  File "D:\@3 深度学习\案例\@6 WZCQ-main 用强化学习训练AI玩王者荣耀\WZCQ-main\模型_策略梯度.py", line 88, in get_model
    model.load_state_dict(torch.load(f'{opt.load_weights}/' + model_weights))
  File `"C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\lib\site-packages\torch\serialization.py",` line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\gavin\.conda\envs\PyTorch19_GPU_Py38\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

Process finished with exit code 1`

**Comment by FengQuanLi** [comment]
可能是模型下载不完全造成的。
你可以保存一个初始化的模型，对比一下下载的模型，看看是不是一样大。
