### ISSUE TITLE
我想请教一下这个报错，不太熟悉这个，想请教一下torchtext.data' has no attribute 'Iterator

### ISSUE THREAD

**Issue by hl123-123** [FengQuanLi/ResnetGPT#42]
Traceback (most recent call last):
  File "F:\python\python_honorAI\训练数据截取_A.py", line 5, in <module>
    from Batch import create_masks
  File "F:\python\python_honorAI\Batch.py", line 31, in <module>
    class MyIterator(data.Iterator):
AttributeError: module 'torchtext.data' has no attribute 'Iterator'

**Comment by FengQuanLi** [comment]
把用到 torchtext模块的类注释掉就好了
实际上是没用这个模块的

**Comment by greenhandzdl** [comment]
[尝试修复](https://github.com/FengQuanLi/ResnetGPT/pull/43)
