### ISSUE TITLE
想问一下，大佬之前调试代码时是否遇到过这个问题？

### ISSUE THREAD

**Issue by xiaoxiaoyuxieing** [FengQuanLi/ResnetGPT#5]
Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\connection.py", line 421, in connect
    tls_in_tls=tls_in_tls,
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 429, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "D:\Anaconda\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 817, in __init__
    self.do_handshake()
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "D:\Anaconda\envs\pytorch\lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/86188/Downloads/ResnetGPT-master/训练数据截取_A.py", line 187, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "C:\Users\86188\Downloads\ResnetGPT-master\运行辅助.py", line 12, in __init__
    MNTDevice.__init__(self,ID)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\connection.py", line 92, in __init__
    self.installer = MNTInstaller(device_id)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\connection.py", line 29, in __init__
    self.download_target_mnt()
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\connection.py", line 42, in download_target_mnt
    mnt_path = download_file(target_url)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\pyminitouch\utils.py", line 17, in download_file
    resp = requests.get(target_url)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\pytorch\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by FengQuanLi** [comment]
你用的是安卓10吗？之前有人用安卓10的系统出现过这个问题。ConnectionResetError: [WinError 10054] 
目前minitouch不支持安卓10

**Comment by xiaoxiaoyuxieing** [comment]
> 你用的是安卓10吗？之前有人用安卓10的系统出现过这个问题。ConnectionResetError：[WinError 10054]
> 目前minitouch不支持安卓10

我用的是安卓11，虽然报错了，但是可以正常监测到屏幕进行的操作

**Comment by xiaoxiaoyuxieing** [comment]
> 你用的是安卓10吗？之前有人用安卓10的系统出现过这个问题。ConnectionResetError：[WinError 10054]
> 目前minitouch不支持安卓10

并且我试了安卓9的手机，报错与这个一致

**Comment by xiaoxiaoyuxieing** [comment]
![image](https://user-images.githubusercontent.com/57784413/104404693-3ce49200-5596-11eb-9a91-e4cfb276d17a.png)

**Comment by zhangbonian** [comment]
pyminitouch 需要通过github下载minitouch binary进行安装，下载地址貌似被墙了，导致连接失败。可以手动下载minitouch binary 通过adb push 上传到手机的/data/local/tmp目录，pyminitouch检测到文件存在会跳过下载直接运行
