### ISSUE TITLE
环境都搭建好了，执行“训练数据截取_A”报错，找不到原因

### ISSUE THREAD

**Issue by kely2019** [FengQuanLi/ResnetGPT#9]
``Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
runfile('F:/code/python/ResnetGPT-master/训练数据截取_A.py', wdir='F:/code/python/ResnetGPT-master')
2021-01-22 00:48:52.222 | INFO     | pyminitouch.utils:is_device_connected:56 - device MI 9 online
2021-01-22 00:48:52.223 | INFO     | pyminitouch.connection:__init__:87 - searching a usable port ...
2021-01-22 00:48:54.224 | INFO     | pyminitouch.connection:__init__:89 - device emulator-5554 bind to port 20519
2021-01-22 00:48:54.311 | INFO     | pyminitouch.connection:get_abi:35 - device emulator-5554 is x86
2021-01-22 00:48:54.439 | INFO     | pyminitouch.connection:get_abi:35 - device emulator-5554 is x86
2021-01-22 00:48:54.439 | INFO     | pyminitouch.connection:download_target_mnt:41 - target minitouch url: https://github.com/williamfzc/stf-binaries/raw/master/node_modules/minitouch-prebuilt/prebuilt/x86/bin/minitouch
Traceback (most recent call last):
  File "D:\软件\python3.8\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "D:\软件\python3.8\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\软件\python3.8\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\软件\python3.8\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "D:\软件\python3.8\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "D:\软件\python3.8\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "D:\软件\python3.8\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "D:\软件\python3.8\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000014CFF1E7850>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "D:\软件\python3.8\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\软件\python3.8\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "D:\软件\python3.8\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /williamfzc/stf-binaries/master/node_modules/minitouch-prebuilt/prebuilt/x86/bin/minitouch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014CFF1E7850>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\软件\pycharm\pycharmpj_180908(1)\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\软件\pycharm\pycharmpj_180908(1)\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/code/python/ResnetGPT-master/训练数据截取_A.py", line 188, in <module>
    设备 = MyMNTDevice(_DEVICE_ID)
  File "F:\code\python\ResnetGPT-master\运行辅助.py", line 10, in __init__
    MNTDevice.__init__(self,ID)
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\actions.py", line 117, in __init__
    self.start()
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\actions.py", line 125, in start
    self.server = MNTServer(self.device_id)
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\connection.py", line 92, in __init__
    self.installer = MNTInstaller(device_id)
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\connection.py", line 29, in __init__
    self.download_target_mnt()
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\connection.py", line 42, in download_target_mnt
    mnt_path = download_file(target_url)
  File "D:\软件\python3.8\lib\site-packages\pyminitouch\utils.py", line 17, in download_file
    resp = requests.get(target_url)
  File "D:\软件\python3.8\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\软件\python3.8\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\软件\python3.8\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\软件\python3.8\lib\site-packages\requests\sessions.py", line 677, in send
    history = [resp for resp in gen]
  File "D:\软件\python3.8\lib\site-packages\requests\sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "D:\软件\python3.8\lib\site-packages\requests\sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "D:\软件\python3.8\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\软件\python3.8\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /williamfzc/stf-binaries/master/node_modules/minitouch-prebuilt/prebuilt/x86/bin/minitouch (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000014CFF1E7850>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by FengQuanLi** [comment]
因为你没有安装minitouch,
pyminitouch模块自动安装时向github请求下载minitouch相关文件时失败
需要手动安装minitouch

**Comment by 2563411574** [comment]
你可以用梯子
